### ISSUE TITLE
Lahiri Ayanamsa doesn't work

### ISSUE THREAD

**Issue by Tejaswgupta** [VedAstro/VedAstro#101]
```
https://api.vedastro.org/Calculate/AllHouseData/HouseName/House1/Location/Kanpur,UttarPradesh,India/Time/17:15/19/11/2002/+05:30/Ayanamsa/Lahiri
```

Returns:
```
{'Status': 'Fail', 'Payload': "The input string 'Lahiri' was not in a correct format."}
```

**Comment by sengiv** [comment]
Thank you for raising this issue. It has been fixed ✅
Rebuild your API URL using latest API Builder --> vedastro.org/APIBuilder
![image](https://github.com/VedAstro/VedAstro/assets/43817262/1ed3450d-3576-42a8-b6eb-ced43d80d683)
