### ISSUE TITLE
Slack Link no longer active

### ISSUE THREAD

**Issue by RaviKarrii** [VedAstro/VedAstro#112]
When trying to join slack group. I keep getting below error 

This link is no longer active

To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by sengiv** [comment]
thanks for reporting this, the link must have expired. 
Please tell me where you clicked? from readme?

please try below link 🙏
https://join.slack.com/t/vedastro/shared_invite/zt-1u7pdqjky-hrJZ7e3_vM2dZOmVY8FeHA

**Comment by RaviKarrii** [comment]
Thanks! This worked. 

And yes, I have tried from read me.

**Comment by ar-daniel** [comment]
The slack link is no longer active.
https://join.slack.com/t/vedastro/shared_invite/zt-1rqkyn0vm-A7YncrN4PFPolVxCEBA37Q
I think it expired again.

**Comment by sengiv** [comment]
slack is getting inactive, can post here
