### ISSUE TITLE
KP House constellation lord not matching

### ISSUE THREAD

**Issue by AbhayVivek** [VedAstro/VedAstro#120]
SC of vedastro api - 
https://[vedastroapi.azurewebsites.net/api/Calculate/AllHouseConstellationLord/Location/Delhi,India/Time/01:30/14/02/2024/+05:30/Ayanamsa/KrishnamurtiKP]
![image](https://github.com/VedAstro/VedAstro/assets/143114904/47a5d310-a81b-4961-8904-0ba30ef4ad72)

SC of data from Astrosage
![image](https://github.com/VedAstro/VedAstro/assets/143114904/79261fd6-0da0-4690-b7ef-35a8b6459463)

**Comment by sengiv** [comment]
you got the wrong API URL, this means normal astrology not KP, you have to add "KP" to end of the method
did you check with values from this site? --> https://kpastrologyaiwebstorage.z5.web.core.windows.net/Charts.html

please please use the website link above to verify KP rated data before, if you want to verify any API data use that websites edit button that I showed you, switch the API from the drop down menu after clicking the edit button which looks like a pencil

**Comment by AbhayVivek** [comment]
Got it, Thanks
