### ISSUE TITLE
Ascendant Calculate?

### ISSUE THREAD

**Issue by Intekai** [VedAstro/VedAstro#132]
does the system calculate the ascendant?

**Comment by sengiv** [comment]
ohh yes it does 😁🫡

**API CALL**
https://vedastroapi.azurewebsites.net/api/Calculate/HouseSignName/HouseName/House1/Location/Singapore/Time/00:00/21/06/2024/+08:00

Try out the [API Builder](https://vedastro.org/APIBuilder), that's how the above URL was generated.
📺 You can also watch video guide (little outdated, but can help) --> https://youtu.be/y110RAgIorY?si=nL8JL6XKpGxzPtAD

@Intekai hope it helps...have fun developing 🎈
