### ISSUE TITLE
Regarding the MIT License

### ISSUE THREAD

**Issue by imrsk** [VedAstro/VedAstro#136]
Hi, I was reviewing the license terms for this repository in order to use it for my project and noticed that it is distributed under the MIT License. However, I see that this project uses the SwissEphNet, which is licensed under the GPL-2.0. 

The GPL-2.0 license requires that any derivative work must also be distributed under the GPL-2.0 license unless you have purchased a professional license from "Swiss Ephemeris" team. Could you please confirm whether the MIT license is appropriate for this repository?

**Comment by ByteMyst** [comment]
Good observation
