### ISSUE TITLE
Data Inconsistencies

### ISSUE THREAD

**Issue by sengiv** [VedAstro/VedAstro#90]
A) when I use allplanetdata I get different house numbers for a planet than for example, when I use planetInHouse for the same planet. 

C) some of the house numbers are coming to be different from several online software services - I also own licensed versions of three different software packages and your house positions are different from them. In most cases your degrees are very similar, however you place them in different houses than other other software. Will send some examples later.

I have run several tests on the AllPlanetData versus AllHouseData discrepancy.. 
There is a discrepancy between House Numbers on your code versus commercially available software packages…. Here are the screen shots.

For date Sep 23, 1967 17:30 Bangalore, Jupiter is at 121.736 degrees, or 121 degrees 44’ 58.61” in your code. Your astronomical longitudinal references are correct. Yet its showing Jupiter in Cancer versus Leo. 
Ideally, this should belong to Leo at 1.736 degrees into Leo. The screen shot shows that the code thinks its House 5, in Cancer. 
 
![image001.png](https://github.com/VedAstro/VedAstro/assets/43817262/e482010c-deef-47d8-83fd-05678dbb6137)

Screenshot 2 – Shows how AllPlanetData is showing House6
 
![image002.png](https://github.com/VedAstro/VedAstro/assets/43817262/29632fdc-8d5f-43e5-a900-c64877a56d75)

 
Screenshot 3 – Marked in Red is where stepping through the code shows the problem. This picture shows Jupiter being deposited in House 6 and Leo (which is correct because other software packages indicate that. But screenshot 1 above is showing House 6 as Cancer. 

 ![image003.png](https://github.com/VedAstro/VedAstro/assets/43817262/10162b34-9e70-401b-8738-8cc48926d5fc)

**Comment by cpjois** [comment]
Ran through another set of test code. I am coming to understand that the HousePlanetIsIn method **IS NOT meant to** provide the position of the Planet's Sign (i.e. Leo in this case). The HousePlanetIsIn method **actually provides** the Bhava position for the Bhava Chalit chart. If this is the intent of the HousePlanetIsIn position, then it is doing its job correctly. This is not a bug. 

Some additional comments on the method to indicate its intent will help resolve this confusion.
 
For getting the position of the Planet from Lagna, this method should NOT be used. Example - After finding the PlanetRasiSign, if you need to find out how many houses the Planet/Rasi is away from Lagna, it's best to call the SigntoSign counting method, and that will provide the correct answer. There is no current method to directly find out the position of the Planet from Lagna.

**Comment by sengiv** [comment]
@cpjois brilliant deduction! 🧠
I'm glad it wasn't a bug 😊

Yes, you're absolutely right,
documentation needs work 📝

If its not an inconvenience to you
please correct the comments in C# code,
it will be automatically be visible in API Builder for future users.

**Comment by sengiv** [comment]
Added new todo for implementing `PlanetFromLagna`

https://github.com/VedAstro/VedAstro/issues/92

**Comment by cpjois** [comment]
I am totally happy to do that. However I have not been a user if GitHub for a while. You will have to help me get started with doing it right. I don’t want to mess up something. Just guide me the first time and I will do so. CPOn Sep 19, 2023, at 5:57 PM, Sengiv ***@***.***> wrote:﻿
@cpjois brilliant deduction! 🧠
I'm glad it wasn't a bug 😊
Yes, you're absolutely right,
documentation needs work 📝
If its not an inconvenience to you
please correct the comments in C# code,
it will be automatically be visible in API Builder for future users.

**Comment by sengiv** [comment]
Happy to help you get started.
You can also video call me when you're doing this.

Step 1 : Fork main repo
Step 2 : Clone the forked repo locally 
Step 3 : Open in VS
Step 4 : Make changes 📝
Step 5 : Commit & Push changes to your fork
Step 6 : In GitHub click "Make Pull Request"
Step 7 : Done!

**Comment by sengiv** [comment]
Also @cpjois please don't forget to Star the repo ⭐ 🙏 appreciate your help

![Screenshot_20230920-092032_GitHub.jpg](https://github.com/VedAstro/VedAstro/assets/43817262/330267b0-e222-41f8-98a0-04d3013e4d85)

**Comment by cpjois** [comment]
Update - I have a destiny point and fortune point code ready and tested. We need to pick a time when you can guide me through the steps to upload a new method. On another note - will appreciate it if you can mask out the birth details on issue 91. Since we anyway closed the issue, it’s better to mask out the date. If you want to leave it there then please fix the typo - it’s 27 Sep 1969. Regards,CPOn Sep 19, 2023, at 8:22 PM, Sengiv ***@***.***> wrote:﻿
Also @cpjois please don't forget to Star the repo ⭐ 🙏 appreciate your help

**Comment by sengiv** [comment]
Awesome news! Can't wait.
Please watch this video --> https://www.youtube.com/watch?v=A8JLNOTHDYo
It is a guide on how to add new C# code to VedAstro library

If you have problems following the quide, please feel free to video call me & share your screen to help you get started

Noted on birth details on issue 91

Thank You for your help  🙏

**Comment by cpjois** [comment]
The birth details are on #90. My bad. 

See screenshot. 

 

From: Sengiv ***@***.***>
Reply-To: VedAstro/VedAstro ***@***.***>
Date: Friday, September 22, 2023 at 7:23 AM
To: VedAstro/VedAstro ***@***.***>
Cc: firstinflight ***@***.***>, Mention ***@***.***>
Subject: Re: [VedAstro/VedAstro] Data Inconsistencies (Issue #90)

 

Awesome news! Can't wait.
Please watch this video --> https://www.youtube.com/watch?v=A8JLNOTHDYo
It is a guide on how to add new C# code to VedAstro library

If you have problems following the quide, please feel free to video call me & share your screen to help you get started

Noted on birth details on issue 91

Thank You for your help  🙏

**Comment by cpjois** [comment]
For time zone, you are in Malaysia, correct? 

 

From: Sengiv ***@***.***>
Reply-To: VedAstro/VedAstro ***@***.***>
Date: Friday, September 22, 2023 at 7:23 AM
To: VedAstro/VedAstro ***@***.***>
Cc: firstinflight ***@***.***>, Mention ***@***.***>
Subject: Re: [VedAstro/VedAstro] Data Inconsistencies (Issue #90)

 

Awesome news! Can't wait.
Please watch this video --> https://www.youtube.com/watch?v=A8JLNOTHDYo
It is a guide on how to add new C# code to VedAstro library

If you have problems following the quide, please feel free to video call me & share your screen to help you get started

Noted on birth details on issue 91

Thank You for your help  🙏
